### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by tomgao365** [MaxLeiter/sortablejs-vue3#1]
```log
sortablejs-vue3 version:
1.0.0

Yarn version: 
  1.22.18

Node version: 
  14.19.3

Platform: 
  win32 x64

Trace: 
  Invariant Violation: expected hoisted manifest for "sortablejs-vue3#vue#@vue/server-renderer#@vue/compiler-ssr"
      at invariant (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:2314:15)
      at _loop2 (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:91022:9)
      at PackageHoister.init (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:91092:19)
      at PackageLinker.getFlatHoistedTree (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:48541:20)
      at PackageLinker.<anonymous> (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:48552:27)
      at Generator.next (<anonymous>)
      at step (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:310:30)
      at D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:328:14
      at new Promise (<anonymous>)
      at new F (D:\Server\nodejs\nvm\v14.19.3\node_modules\yarn\lib\cli.js:5301:28)
```

**Comment by MaxLeiter** [comment]
Huh, never seen that before. Can you try deleting yarn.lock and run `yarn` again?

**Comment by tomgao365** [comment]
you are right! 
I have removed yarn.lock and re-executed yarn install , that has solved the problem.
Thanks，I can't wait to try this library.😀
